//create user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"user",
    "email":"user@gmail.com",
    "password":"user123",
    "hp" : "085768987565",
    "confPassword":"user123",
    "role":"admin"
}

###
//get all userd
GET http://localhost:5000/users

###
//get single user
GET http://localhost:5000/users/eb9b70fe-d7b8-40ff-840a-2565bb3ddb16

###
//update user
PATCH http://localhost:5000/users/96083ff9-d966-46b1-8b03-8f05d4f9044a
Content-Type: application/json

{
    "name":"rendi update",
    "email":"admin@gmail.com",
    "password":"",
    "confPassword":"",
    "role":"user"
}

###
//delete
DELETE http://localhost:5000/users/6f803a0f-b4d6-4e1c-9e06-b9ee20e541b1


###
//me
GET  http://localhost:5000/me

###
//login
POST  http://localhost:5000/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"admin123"
}

###
//logout
DELETE http://localhost:5000/logout

###
//create transaction
POST http://localhost:5000/transaction
Content-Type: application/json

{   
    "name":"sasas21",
    "price":100,
    "lunas":"lunas",
    "tanggal":"Wed Nov 23 2022",
    "timeid":"58bf60f0-6972-11ed-80ec-00155d6ca220"
}
###
//create jadwal
POST http://localhost:5000/createjadwal
Content-Type: application/json

{   
    "jam":"11:00"
}
###
//get all trans
GET http://localhost:5000/transaction
###
//get all trans
GET http://localhost:5000/usertrans/3c7c7f02-4158-49a3-b35e-c7a37304a928

###
//get jadwal
GET http://localhost:5000/getjadwal
###

###
//get qr
GET http://localhost:5000/getqr/silsah2&&4000

###
//get code
GET http://localhost:5000/getcode/silhouette-1669918367780

###
post https://api.xendit.co/callback_virtual_accounts/external_id=va-324123235/simulate_payment

###
//
post http://localhost:5000/qrcall
# Content-Type: application/json

# {   
#     "qrid":"silhouette-1669901551562"
# }
###
get http://localhost:5000/getjadwal/Wed Nov 24 2022

###
post http://localhost:5000/update
Content-Type: application/json

{   
    "qrid":"silhouette-1669911165388"
}

###
get http://localhost:5000/getjadwalid/58bf60f0-6972-11ed-80ec-00155d6ca220
###
//get all trans
GET http://localhost:5000/transaction/silhouette-1669911165388

